services:
  - type: web
    name: leave-management-system
    env: python
    region: singapore
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      mkdir -p instance
      chmod 777 instance
      python -c "from app import app, db, User; app.app_context().push(); db.create_all(); admin = User.query.filter_by(username='admin').first(); print('Admin user exists:', admin is not None)"
    startCommand: |
      python -c "from app import app, init_db; app.app_context().push(); init_db()" && gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_APP
        value: app.py
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: SQLALCHEMY_DATABASE_URI
        value: sqlite:///instance/leave_management.db 